version: "3"
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - "${MOUNT_FOLDER:-./data}/postgresql:/var/lib/postgresql/data"
    networks:
      - postgresql-net
networks:
  postgresql-net:
    driver: bridge
volumes:
  postgresql:


