version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - "${MOUNT_FOLDER:-./data}/zookeeper/data:/var/lib/zookeeper/data"
      - "${MOUNT_FOLDER:-./data}/zookeeper/log:/var/lib/zookeeper/log"
    networks:
      - kafka-net
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: ${KAFKA_MESSAGE_MAX_BYTES}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MAX_PARTITION_FETCH_BYTES: ${KAFKA_MAX_PARTITION_FETCH_BYTES}
      KAFKA_MAX_POLL_RECORDS: ${KAFKA_MAX_POLL_RECORDS}
      KAFKA_FETCH_MAX_BYTES: ${KAFKA_FETCH_MAX_BYTES}
      KAFKA_FETCH_MAX_WAIT_MS: ${KAFKA_FETCH_MAX_WAIT_MS}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
    volumes:
      - "${MOUNT_FOLDER:-./data}/kafka/data:/var/lib/kafka/data"
      - "${MOUNT_FOLDER:-./data}/kafka/log:/var/lib/kafka/log"
    networks:
      - kafka-net
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - 8000:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: broker-9092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
volumes:
  kafka:
  zookeeper: