version: "3"
services:
  redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - redis-net
    volumes:
      - "${MOUNT_FOLDER:-./data}/redis:/data"
  redis-insight:
    image: redislabs/redisinsight
    restart: always
    ports:
      - 8001:8001
    networks:
      - redis-net
    volumes:
      - "${MOUNT_FOLDER:-./data}/redisinsight:/db"
    depends_on:
      - redis
networks:
  redis-net:
    driver: bridge
volumes:
  redis:
  redis-insight: